import { NavLink } from 'react-router-dom'
import { Building2, CalendarClock, FileText, GraduationCap, LayoutDashboard, MessageSquare, UserCog, Users } from 'lucide-react'
import { cn } from '@/lib/utils'
import { useAuthStore } from '@/stores/auth-store'

interface Item { label: string; to: string; icon: React.ComponentType<{ className?: string }> }
const studentServices: Item[] = [{label:'学生首页',to:'/student-assistant',icon:GraduationCap},{label:'客服咨询',to:'/customer-service',icon:MessageSquare}]
const staff: Item[] = [{label:'企业运营',to:'/enterprise-assistant',icon:Building2},{label:'客户研判',to:'/customer-assessment',icon:Users},{label:'授权学生服务',to:'/student-assistant',icon:GraduationCap}]
const management: Item[] = [{label:'管理首页',to:'/dashboard',icon:LayoutDashboard},{label:'智能报告',to:'/reports',icon:FileText},{label:'用户与角色',to:'/admin/users',icon:UserCog},{label:'报告计划',to:'/reports/schedules',icon:CalendarClock}]

export default function Sidebar(){const user=useAuthStore(s=>s.user);const role=user?.role_code;const isManagement=role==='admin'||role==='manager';const items=role==='student'?studentServices:isManagement?[...management,{label:'咨询用户端',to:'/customer-service',icon:MessageSquare},{label:'学生门户预览',to:'/student-assistant?preview=student',icon:GraduationCap}]:staff;return <aside className="fixed left-0 top-0 z-40 flex h-screen w-56 flex-col bg-sidebar-background text-sidebar-foreground"><div className="flex h-16 items-center border-b border-sidebar-border px-5"><div><p className="font-semibold text-white">粹教智服</p><p className="text-[10px] text-sidebar-foreground/60">{role==='student'?'学生门户':isManagement?'管理门户':'员工门户'}</p></div></div><nav className="flex-1 space-y-1 overflow-y-auto p-3">{items.map(item=>{const Icon=item.icon;return <NavLink key={item.to} to={item.to} className={({isActive})=>cn('flex items-center gap-3 rounded-md px-3 py-2 text-sm',isActive?'bg-sidebar-primary text-white':'hover:bg-sidebar-accent')}><Icon className="h-4 w-4"/><span>{item.label}</span></NavLink>})}</nav><div className="border-t border-sidebar-border p-4"><p className="truncate text-sm text-white">{user?.real_name||user?.username}</p><p className="text-xs text-sidebar-foreground/60">{role}</p></div></aside>}
