import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { createUser, getRoles, getUsers } from '@/api/admin-users'
import PageHeader from '@/components/shared/PageHeader'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import LoadingState from '@/components/shared/LoadingState'
import ErrorState from '@/components/shared/ErrorState'

const typeFor = (code: string) => code === 'student' ? 'student' : code === 'admin' ? 'admin' : 'employee'
export default function UserManagementPage() { const qc = useQueryClient(); const [username,setUsername]=useState(''); const [password,setPassword]=useState(''); const [name,setName]=useState(''); const [roleId,setRoleId]=useState(''); const roles=useQuery({queryKey:['roles'],queryFn:getRoles}); const users=useQuery({queryKey:['users'],queryFn:getUsers}); const role=useMemo(()=>roles.data?.items.find(x=>x.id===Number(roleId)),[roles.data,roleId]); const create=useMutation({mutationFn:()=>createUser({username,password,real_name:name,user_type:typeFor(role!.role_code),role_id:Number(roleId)}),onSuccess:async()=>{setUsername('');setPassword('');setName('');setRoleId('');await qc.invalidateQueries({queryKey:['users']})}}); return <div><PageHeader title="用户与角色" description="创建学生或员工登录账号；密码只提交到认证接口。" /><div className="grid gap-6 xl:grid-cols-[360px_1fr]"><Card><CardHeader><CardTitle>创建账号</CardTitle></CardHeader><CardContent className="space-y-4"><div><Label htmlFor="new-user">用户名</Label><Input id="new-user" value={username} onChange={e=>setUsername(e.target.value)} autoComplete="off" /></div><div><Label htmlFor="new-pass">初始密码</Label><Input id="new-pass" type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password" /></div><div><Label htmlFor="new-name">姓名</Label><Input id="new-name" value={name} onChange={e=>setName(e.target.value)} /></div><div><Label>角色</Label><Select value={roleId} onValueChange={setRoleId}><SelectTrigger><SelectValue placeholder="选择角色" /></SelectTrigger><SelectContent>{roles.data?.items.map(x=><SelectItem key={x.id} value={String(x.id)}>{x.role_name}</SelectItem>)}</SelectContent></Select></div><Button className="w-full" disabled={!username||!password||!name||!role||create.isPending} onClick={()=>{if(window.confirm(`确认创建账号 ${username}？`))create.mutate()}}>创建账号</Button>{create.isError&&<ErrorState title="创建失败" message="请检查用户名是否重复。" />}</CardContent></Card><Card><CardHeader><CardTitle>账号目录</CardTitle></CardHeader><CardContent>{users.isLoading&&<LoadingState />}{users.isError&&<ErrorState onRetry={()=>users.refetch()} />}<div className="space-y-2">{users.data?.items.map(x=><div key={x.id} className="flex items-center justify-between rounded border p-3"><div><p className="font-medium">{x.real_name}</p><p className="text-xs text-muted-foreground">{x.username} · {x.user_type}</p></div><span className="text-xs">{x.status}</span></div>)}</div></CardContent></Card></div></div> }
